# generated by datamodel-codegen:
#   filename:  0

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import Field

from ....public.base import PlaygroundBaseModel


class Resolution(Enum):
    field_480p = '480p'
    field_720p = '720p'
    field_1080p = '1080p'


class AspectRatio(Enum):
    field_21_9 = '21:9'
    field_16_9 = '16:9'
    field_4_3 = '4:3'
    field_1_1 = '1:1'
    field_3_4 = '3:4'
    field_9_16 = '9:16'
    field_9_21 = '9:21'


class Duration(Enum):
    integer_5 = 5
    integer_10 = 10


class Input(PlaygroundBaseModel):
    prompt: str = Field(..., description='', title='Prompt')
    resolution: Optional[Resolution] = Field('480p', description='', title='Resolution')
    aspect_ratio: Optional[AspectRatio] = Field(
        '9:16', description='', title='Aspect Ratio (W:H)'
    )
    duration: Optional[Duration] = Field(5, description='', title='Duration')
