# generated by datamodel-codegen:
#   filename:  0

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import Field

from ....public.base import PlaygroundBaseModel


class Resolution(Enum):
    field_480p = '480p'
    field_720p = '720p'
    field_1080p = '1080p'


class Duration(Enum):
    integer_5 = 5
    integer_10 = 10


class Input(PlaygroundBaseModel):
    prompt: str = Field(..., description='', title='Prompt')
    resolution: Optional[Resolution] = Field('480p', description='', title='Resolution')
    image_url: str = Field(..., description='', title='Image')
    duration: Optional[Duration] = Field(5, description='', title='Duration')
